"""منطق العمل (Business Logic)."""

from .auth_service import (
    AuthenticatedSession,
    AuthError,
    ConflictingAccountsError,
    InactiveAccountError,
    InvalidCredentialsError,
    login,
    resolve_current_user,
)
from .audit_service import (
    AuditError,
    AuditPermissionError,
    list_events,
    record,
    record_for,
)
from .audit_store import (
    KNOWN_ACTIONS,
    AuditEvent,
    AuditStore,
    MemoryAuditStore,
    get_audit_store,
)
from .chat_service import send_message
from .conversation_service import (
    ConversationError,
    ConversationNotFoundError,
    context_messages,
    create_conversation,
    delete_conversation,
    derive_title,
    ensure_conversation,
    get_conversation,
    list_conversations,
    list_messages,
    record_exchange,
    rename_conversation,
)
from .conversation_store import (
    Conversation,
    ConversationStore,
    ConversationStoreError,
    MemoryConversationStore,
    Message,
    Page,
    get_conversation_store,
)
from .file_service import (
    FileError,
    FileNotFoundInScopeError,
    FilePermissionError,
    FileStorageError,
    UploadResult,
    can_modify,
    delete_file,
    get_file,
    list_files,
    upload_file,
)
from .model_settings_service import (
    ModelSettingsError,
    read_model_settings,
    resolve_provider_name,
    update_model_settings,
)
from .organization_settings_store import (
    SUBSCRIPTION_STATUSES,
    MemoryOrganizationSettingsStore,
    ModelSettings,
    OrganizationSettingsStore,
    Subscription,
    get_organization_settings_store,
)
from .subscription_service import (
    SeatLimitReachedError,
    SubscriptionError,
    SubscriptionInactiveError,
    ensure_active,
    ensure_seat_available,
    provision_subscription,
    read_subscription,
    seat_usage,
    update_subscription,
)
from .file_store import (
    FileRecord,
    FileStore,
    FileStoreError,
    MemoryFileStore,
    get_file_store,
)
from .directory_service import (
    ALLOWED_ROLES,
    DirectoryError,
    NotFoundError,
    PermissionDeniedError,
    create_organization,
    create_user,
    deactivate_user,
    get_organization,
    get_user,
    list_users,
    update_organization,
    update_user,
)
from .user_store import (
    SUPPORTED_DATA_STORES,
    DuplicateEmailError,
    DuplicateSlugError,
    MemoryUserStore,
    Organization,
    OracleUserStore,
    StoredUser,
    User,
    UserRole,
    UserStore,
    UserStoreError,
    get_user_store,
    normalize_email,
)
from .chunking import ChunkingError, TextChunk, chunk_text, normalize_text
from .rag_service import RetrievalOutcome, build_context_block, retrieve_context
from .retrieval import (
    SUPPORTED_RETRIEVAL_PROVIDERS,
    ChunkStore,
    MemoryChunkStore,
    OracleChunkStore,
    RetrievalError,
    RetrievedChunk,
    cosine_similarity,
    get_chunk_store,
    search_relevant_chunks,
)
from .document_service import (
    IngestionResult,
    ProcessedDocument,
    ingest_document,
    process_document,
)
from .text_extraction import (
    SUPPORTED_EXTENSIONS,
    CorruptFileError,
    EmptyDocumentError,
    FileExtractionError,
    FileTooLargeError,
    UnsupportedFileTypeError,
    extract_text,
    validate_upload,
)

__all__ = [
    "send_message",
    # الاشتراك والتراخيص
    "SUBSCRIPTION_STATUSES",
    "MemoryOrganizationSettingsStore",
    "OrganizationSettingsStore",
    "SeatLimitReachedError",
    "Subscription",
    "SubscriptionError",
    "SubscriptionInactiveError",
    "ensure_active",
    "ensure_seat_available",
    "get_organization_settings_store",
    "provision_subscription",
    "read_subscription",
    "seat_usage",
    "update_subscription",
    # مزود المودل لكل جهة
    "ModelSettings",
    "ModelSettingsError",
    "read_model_settings",
    "resolve_provider_name",
    "update_model_settings",
    # سجل التدقيق
    "KNOWN_ACTIONS",
    "AuditError",
    "AuditEvent",
    "AuditPermissionError",
    "AuditStore",
    "MemoryAuditStore",
    "get_audit_store",
    "list_events",
    "record",
    "record_for",
    # المحادثات والرسائل
    "Conversation",
    "ConversationError",
    "ConversationNotFoundError",
    "ConversationStore",
    "ConversationStoreError",
    "MemoryConversationStore",
    "Message",
    "Page",
    "context_messages",
    "create_conversation",
    "delete_conversation",
    "derive_title",
    "ensure_conversation",
    "get_conversation",
    "get_conversation_store",
    "list_conversations",
    "list_messages",
    "record_exchange",
    "rename_conversation",
    # الملفات
    "FileError",
    "FileNotFoundInScopeError",
    "FilePermissionError",
    "can_modify",
    "delete_file",
    "FileRecord",
    "FileStorageError",
    "FileStore",
    "FileStoreError",
    "MemoryFileStore",
    "UploadResult",
    "get_file",
    "get_file_store",
    "list_files",
    "upload_file",
    # المصادقة
    "AuthError",
    "AuthenticatedSession",
    "ConflictingAccountsError",
    "InactiveAccountError",
    "InvalidCredentialsError",
    "login",
    "resolve_current_user",
    # الجهات والمستخدمون — المخزن
    "SUPPORTED_DATA_STORES",
    "DuplicateEmailError",
    "DuplicateSlugError",
    "MemoryUserStore",
    "Organization",
    "OracleUserStore",
    "StoredUser",
    "User",
    "UserRole",
    "UserStore",
    "UserStoreError",
    "get_user_store",
    "normalize_email",
    # الجهات والمستخدمون — الإدارة والصلاحيات
    "ALLOWED_ROLES",
    "DirectoryError",
    "NotFoundError",
    "PermissionDeniedError",
    "create_organization",
    "create_user",
    "deactivate_user",
    "get_organization",
    "get_user",
    "list_users",
    "update_organization",
    "update_user",
    # التقطيع
    "ChunkingError",
    "TextChunk",
    "chunk_text",
    "normalize_text",
    # استخراج النص
    "SUPPORTED_EXTENSIONS",
    "CorruptFileError",
    "EmptyDocumentError",
    "FileExtractionError",
    "FileTooLargeError",
    "UnsupportedFileTypeError",
    "extract_text",
    "validate_upload",
    # البحث المتجهي (RAG)
    "SUPPORTED_RETRIEVAL_PROVIDERS",
    "ChunkStore",
    "MemoryChunkStore",
    "OracleChunkStore",
    "RetrievalError",
    "RetrievalOutcome",
    "RetrievedChunk",
    "build_context_block",
    "cosine_similarity",
    "get_chunk_store",
    "retrieve_context",
    "search_relevant_chunks",
    # المسار الكامل
    "IngestionResult",
    "ProcessedDocument",
    "ingest_document",
    "process_document",
]
