-- ============================================================
-- GovAgent - مخطط قاعدة البيانات (Oracle)
--
-- نسخة MVP لمشروع تخرج. تسعة جداول فقط.
-- مبدأ العزل: كل صف يخص جهة يحمل organization_id، وكل استعلام في الـBackend
-- يجب أن يُقيَّد بـorganization_id للمستخدم الحالي.
--
-- التشغيل وخطواته: database/README.md
-- الترتيب مهم بسبب المفاتيح الأجنبية: نفّذ الملف من أعلى إلى أسفل.
--
-- المتطلبات:
--   * Oracle 23ai أو أحدث لعمود VECTOR في جدول document_chunks (جدول 7).
--     على نسخة أقدم يفشل ذلك الجدول وحده — انظر التعليق فوقه.
--   * ترميز القاعدة AL32UTF8 لتخزين العربية.
--   * قاعدة نظيفة: الملف لا يحتوي DROP، فتشغيله مرتين يفشل بـORA-00955.
--     لإعادة التشغيل نفّذ database/drop_all.sql أولًا.
--
-- ملاحظة على updated_at: القيمة الافتراضية تُملأ عند الإدراج فقط. تحديثها
-- عند كل تعديل مسؤولية الـBackend (SET updated_at = SYSTIMESTAMP)، ولا يوجد
-- Trigger هنا عمدًا ليبقى الملف قابلًا للتشغيل كسكربت SQL عادي.
-- ============================================================


-- ------------------------------------------------------------
-- 1) organizations - الجهات الحكومية المشتركة في النظام
-- ------------------------------------------------------------
CREATE TABLE organizations (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(200 CHAR)  NOT NULL,
    -- معرّف نصي قصير يستخدم في الروابط، مثل: ministry-x
    slug            VARCHAR2(60 CHAR)   NOT NULL,
    is_active       NUMBER(1)      DEFAULT 1 NOT NULL,
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT uq_organizations_slug UNIQUE (slug),
    CONSTRAINT ck_organizations_active CHECK (is_active IN (0, 1))
);


-- ------------------------------------------------------------
-- 2) users - موظفو الجهة ومسؤولوها
-- دوران فقط: admin و employee.
-- ------------------------------------------------------------
CREATE TABLE users (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id NUMBER         NOT NULL,
    email           VARCHAR2(200 CHAR)  NOT NULL,
    full_name       VARCHAR2(200 CHAR)  NOT NULL,
    -- تُخزَّن كلمة المرور مُجزّأة (bcrypt) فقط. يمنع تخزين النص الصريح.
    password_hash   VARCHAR2(255 CHAR)  NOT NULL,
    role            VARCHAR2(20 CHAR)   DEFAULT 'employee' NOT NULL,
    is_active       NUMBER(1)      DEFAULT 1 NOT NULL,
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_users_org FOREIGN KEY (organization_id)
        REFERENCES organizations (id),
    -- البريد فريد داخل الجهة الواحدة، لا على مستوى النظام كله.
    CONSTRAINT uq_users_org_email UNIQUE (organization_id, email),
    CONSTRAINT ck_users_role CHECK (role IN ('admin', 'employee')),
    CONSTRAINT ck_users_active CHECK (is_active IN (0, 1))
);

-- لا فهرس منفصل على organization_id: قيد uq_users_org_email يبدأ بالعمود
-- نفسه، وفهرسه الضمني يخدم استعلامات العزل.


-- ------------------------------------------------------------
-- 3) subscriptions - اشتراك الجهة وعدد التراخيص
-- لا يوجد جدول licenses منفصل في الـMVP: عدد التراخيص حقل هنا،
-- والمستخدَم منها = عدد المستخدمين النشطين في الجهة.
-- ------------------------------------------------------------
CREATE TABLE subscriptions (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id NUMBER         NOT NULL,
    status          VARCHAR2(20 CHAR)   DEFAULT 'active' NOT NULL,
    seats           NUMBER(6)      DEFAULT 10 NOT NULL,
    starts_at       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    expires_at      TIMESTAMP      NOT NULL,
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_subscriptions_org FOREIGN KEY (organization_id)
        REFERENCES organizations (id),
    -- اشتراك واحد فعّال لكل جهة في الـMVP.
    CONSTRAINT uq_subscriptions_org UNIQUE (organization_id),
    CONSTRAINT ck_subscriptions_status
        CHECK (status IN ('active', 'expired', 'suspended')),
    CONSTRAINT ck_subscriptions_seats CHECK (seats > 0)
);


-- ------------------------------------------------------------
-- 4) conversations - محادثات الموظف
-- المحادثة خاصة بصاحبها: كل استعلام يُقيَّد بـuser_id و organization_id.
-- ------------------------------------------------------------
CREATE TABLE conversations (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id NUMBER         NOT NULL,
    user_id         NUMBER         NOT NULL,
    title           VARCHAR2(300 CHAR)  DEFAULT 'محادثة جديدة' NOT NULL,
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_conversations_org FOREIGN KEY (organization_id)
        REFERENCES organizations (id),
    CONSTRAINT fk_conversations_user FOREIGN KEY (user_id)
        REFERENCES users (id)
);

-- الاستعلام الأكثر تكرارًا: محادثات موظف واحد مرتبة بالأحدث.
CREATE INDEX ix_conversations_user ON conversations (user_id, updated_at DESC);


-- ------------------------------------------------------------
-- 5) messages - رسائل المحادثة
-- ------------------------------------------------------------
CREATE TABLE messages (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id NUMBER         NOT NULL,
    organization_id NUMBER         NOT NULL,
    role            VARCHAR2(20 CHAR)   NOT NULL,
    content         CLOB           NOT NULL,
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

    -- حذف المحادثة يحذف رسائلها: الرسالة لا معنى لها بدون محادثتها.
    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id)
        REFERENCES conversations (id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_org FOREIGN KEY (organization_id)
        REFERENCES organizations (id),
    CONSTRAINT ck_messages_role CHECK (role IN ('user', 'assistant'))
);

CREATE INDEX ix_messages_conversation ON messages (conversation_id, created_at);


-- ------------------------------------------------------------
-- 6) files - بيانات الملفات المرفوعة (PDF / Word / TXT)
-- الملف نفسه يُخزَّن على قرص السيرفر، وهنا بياناته الوصفية فقط.
-- ------------------------------------------------------------
CREATE TABLE files (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id NUMBER         NOT NULL,
    user_id         NUMBER         NOT NULL,
    conversation_id NUMBER,
    original_name   VARCHAR2(300 CHAR)  NOT NULL,
    storage_path    VARCHAR2(500 CHAR)  NOT NULL,
    mime_type       VARCHAR2(120 CHAR)  NOT NULL,
    size_bytes      NUMBER(12)     NOT NULL,
    -- pending -> processed | failed  (حالة استخراج النص)
    status          VARCHAR2(20 CHAR)   DEFAULT 'pending' NOT NULL,
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_files_org FOREIGN KEY (organization_id)
        REFERENCES organizations (id),
    CONSTRAINT fk_files_user FOREIGN KEY (user_id)
        REFERENCES users (id),
    -- الملف يبقى بعد حذف المحادثة، وتُفرَّغ الصلة فقط.
    CONSTRAINT fk_files_conversation FOREIGN KEY (conversation_id)
        REFERENCES conversations (id) ON DELETE SET NULL,
    CONSTRAINT ck_files_status
        CHECK (status IN ('pending', 'processed', 'failed')),
    CONSTRAINT ck_files_size CHECK (size_bytes > 0)
);

CREATE INDEX ix_files_user ON files (user_id, created_at DESC);


-- ------------------------------------------------------------
-- 7) document_chunks - مقاطع نصية من الملفات للبحث (RAG)
--
-- عمود embedding من نوع VECTOR يتطلب Oracle 23ai أو أحدث. تُرك بلا أبعاد
-- محددة عمدًا (VECTOR وليس VECTOR(1024, FLOAT32)) حتى لا يرتبط المخطط بمودل
-- Embedding بعينه قبل اختياره في P1-03.
--
-- على نسخة أقدم من 23ai يفشل هذا الجدول وحده بـORA-00902. الحل: احذف سطر
-- embedding وأكمل بالبحث النصي، أو رقِّ القاعدة إلى 23ai.
--
-- فهرس التسريع المتجهي (VECTOR INDEX) غير مضاف هنا عمدًا: يُنشأ في P1-04 بعد
-- تثبيت مقياس المسافة وعدد الأبعاد، وإضافته الآن قد تفشل حسب نسخة القاعدة.
-- ------------------------------------------------------------
CREATE TABLE document_chunks (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id         NUMBER         NOT NULL,
    organization_id NUMBER         NOT NULL,
    chunk_index     NUMBER(8)      NOT NULL,
    content         CLOB           NOT NULL,
    embedding       VECTOR,
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

    -- حذف الملف يحذف مقاطعه: المقطع لا معنى له بدون ملفه.
    CONSTRAINT fk_chunks_file FOREIGN KEY (file_id)
        REFERENCES files (id) ON DELETE CASCADE,
    CONSTRAINT fk_chunks_org FOREIGN KEY (organization_id)
        REFERENCES organizations (id),
    CONSTRAINT uq_chunks_file_index UNIQUE (file_id, chunk_index)
);

CREATE INDEX ix_chunks_org ON document_chunks (organization_id);


-- ------------------------------------------------------------
-- 8) model_settings - مزود المودل المختار لكل جهة
-- لا تُخزَّن هنا أي مفاتيح أو أسرار. بيانات اعتماد OCI تبقى في
-- متغيرات البيئة على السيرفر، خارج قاعدة البيانات وخارج المستودع.
-- ------------------------------------------------------------
CREATE TABLE model_settings (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id NUMBER         NOT NULL,
    provider        VARCHAR2(20 CHAR)   DEFAULT 'mock' NOT NULL,
    updated_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_model_settings_org FOREIGN KEY (organization_id)
        REFERENCES organizations (id),
    CONSTRAINT uq_model_settings_org UNIQUE (organization_id),
    CONSTRAINT ck_model_settings_provider
        CHECK (provider IN ('mock', 'oracle', 'local'))
);


-- ------------------------------------------------------------
-- 9) audit_logs - سجل بسيط للأحداث المهمة
-- أمثلة action: login, user_created, user_disabled,
--               model_provider_changed, file_uploaded
-- ------------------------------------------------------------
CREATE TABLE audit_logs (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id NUMBER         NOT NULL,
    user_id         NUMBER,
    action          VARCHAR2(60 CHAR)   NOT NULL,
    details         VARCHAR2(1000 CHAR),
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_audit_org FOREIGN KEY (organization_id)
        REFERENCES organizations (id),
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id)
        REFERENCES users (id)
);

CREATE INDEX ix_audit_org_time ON audit_logs (organization_id, created_at DESC);
